### ISSUE TITLE
Some feedback and some questions

### ISSUE THREAD

**Issue by EricSchles** [zelros/cinnamon#5]
Hi!

This looks like a great project!  I have a few concerns about using a hypothesis based test for comparison of drift - reason being, how do you account for the multiple comparison's problem?  https://en.wikipedia.org/wiki/Multiple_comparisons_problem

You do get some more explanatory power by looking at the plots, to be sure.  I was thinking maybe you could include some permutation tests to deal with this, instead of relying on KS?  Here is a reference: http://sia.webpopix.org/statisticalTests2.html and here is some in Python: https://ericschles.github.io/cuny_intro_to_ds_book/12/1/AB_Testing.html?highlight=permutation (important to note even though this is my teaching resource, it is lifted from some content from berkeley).

Anyway, great job!

**Comment by YohannLeFaou** [comment]
Hi Eric,

Thanks for the feedback!

From the experiments I have made the problem with the statistical test used in the context of data drift detection is that when samples are large the test generaly detect a data drift (in real life it is rare that a phenomenom is fully stationnary, at least in the cases I have been studying).

About multiple comparison problem, the solutions would be the same as when we have multiple comparison in the context of A/B test (Bonferroni correction, etc.). Also note that if the test variable is discrete then Chi2 test can handle the multiclass scheme. I agree permutation test is an interesting idea, though it may be require many computations in some cases. Also, we may find some natively multi-dimensional statistical test in some situation (e.g. for the KS test : https://inis.iaea.org/search/search.aspx?orig_q=RN:18067274)

**Comment by EricSchles** [comment]
It looks like the KS generalization sort of does permutation since it’s
doing Monte Carlo simulation.  That sounds like a reasonable notion.  The
permutation test *can* be tough.  Perhaps you could set the permutation
test a possibility and give the user control over when to use it, and set a
hyper parameter for the number of permutations?  Then users can make the
call if they have enough or not enough compute resources to run the test.
I think explaining this in the doc string would probably be enough?  But
maybe some extra context could help people as a guide

**Comment by EricSchles** [comment]
Anything come of this?
